@startuml Forgot Password
    title Forgot Password
    skinparam backgroundColor #EEEEEE
    skinparam shadowing true

    actor User
    control Server
    database Database
    User --> Server : Request password reset
    activate Server  #lightblue
    Server --> Database : Verify User email
    Database --> Server : Confirm User email exists
    Server -> Server : Generate password reset token
    Server --> User : Email password reset link
    deactivate Server 
    User --> Server : Clicks on reset link and submit new password
    activate Server #lightblue
    Server -> Server : Validate new password
    alt If new password is valid
        Server --> Database : Update User password
            Database --> Server : Confirm password updated
            Server --> User : Redirect to login page
    else
        Server --> User : Display form validation error
    end
    deactivate Server
@enduml
